import numpy as np

class Cube(object):
	# Data types
	ERROR = -1
	INT = 0
	FLOAT = 1
	CHAR = 2
	STRING = 3
	BOOLEAN = 4
	NULL = 5
	# Operations
	SUM = 0
	SUBSTRACTION = 1
	MULTIPLICATION = 2
	DIVISION = 3
	POWER = 4
	MOD = 5
	GREATER = 6
	LESS = 7
	GREATER_OR_EQUAL = 8
	LESS_OR_EQUAL = 9
	EQUAL = 10
	NOT_EQUAL = 11
	AND = 12
	OR = 13
	def __init__(self):
		self.cube = np.empty((6, 14, 6))
		# INT + Data types
		self.cube[self.INT, self.SUM, self.INT] = self.INT
		self.cube[self.INT, self.SUM, self.FLOAT] = self.FLOAT
		self.cube[self.INT, self.SUM, self.CHAR] = self.ERROR
		self.cube[self.INT, self.SUM, self.STRING] = self.ERROR
		self.cube[self.INT, self.SUM, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.SUM, self.NULL] = self.ERROR
		# INT - Data types
		self.cube[self.INT, self.SUBSTRACTION, self.INT] = self.INT
		self.cube[self.INT, self.SUBSTRACTION, self.FLOAT] = self.FLOAT
		self.cube[self.INT, self.SUBSTRACTION, self.CHAR] = self.ERROR
		self.cube[self.INT, self.SUBSTRACTION, self.STRING] = self.ERROR
		self.cube[self.INT, self.SUBSTRACTION, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.SUBSTRACTION, self.NULL] = self.ERROR
		# INT * Data types
		self.cube[self.INT, self.MULTIPLICATION, self.INT] = self.INT
		self.cube[self.INT, self.MULTIPLICATION, self.FLOAT] = self.FLOAT
		self.cube[self.INT, self.MULTIPLICATION, self.CHAR] = self.ERROR
		self.cube[self.INT, self.MULTIPLICATION, self.STRING] = self.ERROR
		self.cube[self.INT, self.MULTIPLICATION, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.MULTIPLICATION, self.NULL] = self.ERROR
		# INT / Data types
		self.cube[self.INT, self.DIVISION, self.INT] = self.INT
		self.cube[self.INT, self.DIVISION, self.FLOAT] = self.INT
		self.cube[self.INT, self.DIVISION, self.CHAR] = self.ERROR
		self.cube[self.INT, self.DIVISION, self.STRING] = self.ERROR
		self.cube[self.INT, self.DIVISION, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.DIVISION, self.NULL] = self.ERROR
		# INT MOD Data types
		self.cube[self.INT, self.MOD, self.INT] = self.INT
		self.cube[self.INT, self.MOD, self.FLOAT] = self.FLOAT
		self.cube[self.INT, self.MOD, self.CHAR] = self.ERROR
		self.cube[self.INT, self.MOD, self.STRING] = self.ERROR
		self.cube[self.INT, self.MOD, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.MOD, self.NULL] = self.ERROR
		# INT > Data type
		self.cube[self.INT, self.GREATER, self.INT] = self.BOOLEAN
		self.cube[self.INT, self.GREATER, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.GREATER, self.CHAR] = self.ERROR
		self.cube[self.INT, self.GREATER, self.STRING] = self.ERROR
		self.cube[self.INT, self.GREATER, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.GREATER, self.NULL] = self.ERROR
		# INT < Data types
		self.cube[self.INT, self.LESS, self.INT] = self.BOOLEAN
		self.cube[self.INT, self.LESS, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.LESS, self.CHAR] = self.ERROR
		self.cube[self.INT, self.LESS, self.STRING] = self.ERROR
		self.cube[self.INT, self.LESS, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.LESS, self.NULL] = self.ERROR
		# INT >= Data types
		self.cube[self.INT, self.GREATER_OR_EQUAL, self.INT] = self.BOOLEAN
		self.cube[self.INT, self.GREATER_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.GREATER_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.INT, self.GREATER_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.INT, self.GREATER_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.GREATER_OR_EQUAL, self.NULL] = self.ERROR
		# INT <= Data types
		self.cube[self.INT, self.LESS_OR_EQUAL, self.INT] = self.BOOLEAN
		self.cube[self.INT, self.LESS_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.LESS_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.INT, self.LESS_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.INT, self.LESS_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.LESS_OR_EQUAL, self.NULL] = self.ERROR
		# INT = Data types
		self.cube[self.INT, self.EQUAL, self.INT] = self.INT
		self.cube[self.INT, self.EQUAL, self.FLOAT] = self.FLOAT
		self.cube[self.INT, self.EQUAL, self.CHAR] = self.ERROR
		self.cube[self.INT, self.EQUAL, self.STRING] = self.ERROR
		self.cube[self.INT, self.EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.EQUAL, self.NULL] = self.ERROR
		# INT != Data type
		self.cube[self.INT, self.NOT_EQUAL, self.INT] = self.ERROR
		self.cube[self.INT, self.NOT_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.NOT_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.INT, self.NOT_EQUAL, self.STRING] = self.ERROR
		self.cube[self.INT, self.NOT_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.NOT_EQUAL, self.NULL] = self.ERROR
		# INT && Data types
		self.cube[self.INT, self.AND, self.INT] = self.ERROR
		self.cube[self.INT, self.AND, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.AND, self.CHAR] = self.ERROR
		self.cube[self.INT, self.AND, self.STRING] = self.ERROR
		self.cube[self.INT, self.AND, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.AND, self.NULL] = self.ERROR
		# INT || Data types
		self.cube[self.INT, self.OR, self.INT] = self.ERROR
		self.cube[self.INT, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.INT, self.OR, self.CHAR] = self.ERROR
		self.cube[self.INT, self.OR, self.STRING] = self.ERROR
		self.cube[self.INT, self.OR, self.BOOLEAN] = self.ERROR
		self.cube[self.INT, self.OR, self.NULL] = self.ERROR
		# FLOAT + Data types
		self.cube[self.FLOAT, self.SUM, self.INT] = self.FLOAT
		self.cube[self.FLOAT, self.SUM, self.FLOAT] = self.FLOAT
		self.cube[self.FLOAT, self.SUM, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.SUM, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.SUM, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.SUM, self.NULL] = self.ERROR
		# FLOAT - Data types
		self.cube[self.FLOAT, self.SUBSTRACTION, self.INT] = self.FLOAT
		self.cube[self.FLOAT, self.SUBSTRACTION, self.FLOAT] = self.FLOAT
		self.cube[self.FLOAT, self.SUBSTRACTION, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.SUBSTRACTION, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.SUBSTRACTION, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.SUBSTRACTION, self.NULL] = self.ERROR
		# FLOAT * Data types
		self.cube[self.FLOAT, self.MULTIPLICATION, self.INT] = self.FLOAT
		self.cube[self.FLOAT, self.MULTIPLICATION, self.FLOAT] = self.FLOAT
		self.cube[self.FLOAT, self.MULTIPLICATION, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.MULTIPLICATION, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.MULTIPLICATION, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.MULTIPLICATION, self.NULL] = self.ERROR
		# FLOAT / Data types
		self.cube[self.FLOAT, self.DIVISION, self.INT] = self.INT
		self.cube[self.FLOAT, self.DIVISION, self.FLOAT] = self.FLOAT
		self.cube[self.FLOAT, self.DIVISION, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.DIVISION, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.DIVISION, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.DIVISION, self.NULL] = self.ERROR
		# FLOAT MOD Data types
		self.cube[self.FLOAT, self.MOD, self.INT] = self.FLOAT
		self.cube[self.FLOAT, self.MOD, self.FLOAT] = self.FLOAT
		self.cube[self.FLOAT, self.MOD, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.MOD, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.MOD, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.MOD, self.NULL] = self.ERROR
		# FLOAT > Data type
		self.cube[self.FLOAT, self.GREATER, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.GREATER, self.FLOAT] = self.BOOLEAN
		self.cube[self.FLOAT, self.GREATER, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.GREATER, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.GREATER, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.GREATER, self.NULL] = self.ERROR
		# FLOAT < Data types
		self.cube[self.FLOAT, self.LESS, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.LESS, self.FLOAT] = self.BOOLEAN
		self.cube[self.FLOAT, self.LESS, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.LESS, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.LESS, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.LESS, self.NULL] = self.ERROR
		# FLOAT >= Data types
		self.cube[self.FLOAT, self.GREATER_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.GREATER_OR_EQUAL, self.FLOAT] = self.BOOLEAN
		self.cube[self.FLOAT, self.GREATER_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.GREATER_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.GREATER_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.GREATER_OR_EQUAL, self.NULL] = self.ERROR
		# FLOAT <= Data types
		self.cube[self.FLOAT, self.LESS_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.LESS_OR_EQUAL, self.FLOAT] = self.BOOLEAN
		self.cube[self.FLOAT, self.LESS_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.LESS_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.LESS_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.LESS_OR_EQUAL, self.NULL] = self.ERROR
		# FLOAT = Data types
		self.cube[self.FLOAT, self.EQUAL, self.INT] = self.INT
		self.cube[self.FLOAT, self.EQUAL, self.FLOAT] = self.FLOAT
		self.cube[self.FLOAT, self.EQUAL, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.EQUAL, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.EQUAL, self.NULL] = self.ERROR
		# FLOAT != Data type
		self.cube[self.FLOAT, self.NOT_EQUAL, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.NOT_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.FLOAT, self.NOT_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.NOT_EQUAL, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.NOT_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.NOT_EQUAL, self.NULL] = self.ERROR
		# FLOAT && Data types
		self.cube[self.FLOAT, self.AND, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.AND, self.FLOAT] = self.ERROR
		self.cube[self.FLOAT, self.AND, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.AND, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.AND, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.AND, self.NULL] = self.ERROR
		# FLOAT || Data types
		self.cube[self.FLOAT, self.OR, self.INT] = self.ERROR
		self.cube[self.FLOAT, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.FLOAT, self.OR, self.CHAR] = self.ERROR
		self.cube[self.FLOAT, self.OR, self.STRING] = self.ERROR
		self.cube[self.FLOAT, self.OR, self.BOOLEAN] = self.ERROR
		self.cube[self.FLOAT, self.OR, self.NULL] = self.ERROR
		# Char + Data types
		self.cube[self.CHAR, self.SUM, self.INT] = self.ERROR
		self.cube[self.CHAR, self.SUM, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.SUM, self.CHAR] = self.STRING
		self.cube[self.CHAR, self.SUM, self.STRING] = self.STRING
		self.cube[self.CHAR, self.SUM, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.SUM, self.NULL] = self.ERROR
		# Char - Data types
		self.cube[self.CHAR, self.OR, self.INT] = self.ERROR
		self.cube[self.CHAR, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.OR, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.OR, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.OR, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.OR, self.NULL] = self.ERROR
		# Char * Data types
		self.cube[self.CHAR, self.OR, self.INT] = self.ERROR
		self.cube[self.CHAR, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.OR, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.OR, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.OR, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.OR, self.NULL] = self.ERROR
		# Char / Data types
		self.cube[self.CHAR, self.DIVISION, self.INT] = self.ERROR
		self.cube[self.CHAR, self.DIVISION, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.DIVISION, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.DIVISION, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.DIVISION, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.DIVISION, self.NULL] = self.ERROR
		# Char POWER Data types
		self.cube[self.CHAR, self.POWER, self.INT] = self.ERROR
		self.cube[self.CHAR, self.POWER, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.POWER, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.POWER, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.POWER, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.POWER, self.NULL] = self.ERROR
		# Char MOD Data types
		self.cube[self.CHAR, self.MOD, self.INT] = self.ERROR
		self.cube[self.CHAR, self.MOD, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.MOD, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.MOD, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.MOD, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.MOD, self.NULL] = self.ERROR
		# CHAR GREATER Data types
		self.cube[self.CHAR, self.GREATER, self.INT] = self.ERROR
		self.cube[self.CHAR, self.GREATER, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.GREATER, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.GREATER, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.GREATER, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.GREATER, self.NULL] = self.ERROR
		# CHAR LESS Data types
		self.cube[self.CHAR, self.LESS, self.INT] = self.ERROR
		self.cube[self.CHAR, self.LESS, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.LESS, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.LESS, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.LESS, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.LESS, self.NULL] = self.ERROR
		# CHAR >= Data types
		self.cube[self.CHAR, self.GREATER_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.CHAR, self.GREATER_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.GREATER_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.GREATER_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.GREATER_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.GREATER_OR_EQUAL, self.NULL] = self.ERROR	
		# CHAR <= Data types
		self.cube[self.CHAR, self.LESS_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.CHAR, self.LESS_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.LESS_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.LESS_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.LESS_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.LESS_OR_EQUAL, self.NULL] = self.ERROR
		# CHAR = Data types
		self.cube[self.CHAR, self.EQUAL, self.INT] = self.ERROR
		self.cube[self.CHAR, self.EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.EQUAL, self.CHAR] = self.CHAR
		self.cube[self.CHAR, self.EQUAL, self.STRING] = self.STRING
		self.cube[self.CHAR, self.EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.EQUAL, self.NULL] = self.ERROR
		# CHAR != Data types
		self.cube[self.CHAR, self.NOT_EQUAL, self.INT] = self.ERROR
		self.cube[self.CHAR, self.NOT_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.NOT_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.NOT_EQUAL, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.NOT_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.NOT_EQUAL, self.NULL] = self.ERROR
		# CHAR AND Data types
		self.cube[self.CHAR, self.AND, self.INT] = self.ERROR
		self.cube[self.CHAR, self.AND, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.AND, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.AND, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.AND, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.AND, self.NULL] = self.ERROR
		# CHAR OR Data types
		self.cube[self.CHAR, self.OR, self.INT] = self.ERROR
		self.cube[self.CHAR, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.CHAR, self.OR, self.CHAR] = self.ERROR
		self.cube[self.CHAR, self.OR, self.STRING] = self.ERROR
		self.cube[self.CHAR, self.OR, self.BOOLEAN] = self.ERROR
		self.cube[self.CHAR, self.OR, self.NULL] = self.ERROR
		#  STRING + Data types
		self.cube[self.STRING, self.SUM, self.INT] = self.ERROR
		self.cube[self.STRING, self.SUM, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.SUM, self.CHAR] = self.STRING
		self.cube[self.STRING, self.SUM, self.STRING] = self.STRING
		self.cube[self.STRING, self.SUM, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.SUM, self.NULL] = self.ERROR
		#  STRING - Data types
		self.cube[self.STRING, self.SUBSTRACTION, self.INT] = self.ERROR
		self.cube[self.STRING, self.SUBSTRACTION, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.SUBSTRACTION, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.SUBSTRACTION, self.STRING] = self.ERROR
		self.cube[self.STRING, self.SUBSTRACTION, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.SUBSTRACTION, self.NULL] = self.ERROR
		#  STRING * Data types
		self.cube[self.STRING, self.MULTIPLICATION, self.INT] = self.ERROR
		self.cube[self.STRING, self.MULTIPLICATION, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.MULTIPLICATION, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.MULTIPLICATION, self.STRING] = self.ERROR
		self.cube[self.STRING, self.MULTIPLICATION, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.MULTIPLICATION, self.NULL] = self.ERROR
		#  STRING / Data types
		self.cube[self.STRING, self.DIVISION, self.INT] = self.ERROR
		self.cube[self.STRING, self.DIVISION, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.DIVISION, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.DIVISION, self.STRING] = self.ERROR
		self.cube[self.STRING, self.DIVISION, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.DIVISION, self.NULL] = self.ERROR
		#  STRING Power Data types
		self.cube[self.STRING, self.POWER, self.INT] = self.ERROR
		self.cube[self.STRING, self.POWER, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.POWER, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.POWER, self.STRING] = self.ERROR
		self.cube[self.STRING, self.POWER, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.POWER, self.NULL] = self.ERROR
		#  STRING MOD Data types
		self.cube[self.STRING, self.MOD, self.INT] = self.ERROR
		self.cube[self.STRING, self.MOD, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.MOD, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.MOD, self.STRING] = self.ERROR
		self.cube[self.STRING, self.MOD, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.MOD, self.NULL] = self.ERROR
		#  STRING GREATER Data types
		self.cube[self.STRING, self.GREATER, self.INT] = self.ERROR
		self.cube[self.STRING, self.GREATER, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.GREATER, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.GREATER, self.STRING] = self.ERROR
		self.cube[self.STRING, self.GREATER, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.GREATER, self.NULL] = self.ERROR
		#  STRING LESS Data types
		self.cube[self.STRING, self.LESS, self.INT] = self.ERROR
		self.cube[self.STRING, self.LESS, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.LESS, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.LESS, self.STRING] = self.ERROR
		self.cube[self.STRING, self.LESS, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.LESS, self.NULL] = self.ERROR
		#  STRING >= Data types
		self.cube[self.STRING, self.GREATER_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.STRING, self.GREATER_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.GREATER_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.GREATER_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.STRING, self.GREATER_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.GREATER_OR_EQUAL, self.NULL] = self.ERROR
		#  STRING <= Data types
		self.cube[self.STRING, self.LESS_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.STRING, self.LESS_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.LESS_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.LESS_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.STRING, self.LESS_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.LESS_OR_EQUAL, self.NULL] = self.ERROR
		#  STRING = Data types
		self.cube[self.STRING, self.EQUAL, self.INT] = self.ERROR
		self.cube[self.STRING, self.EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.EQUAL, self.CHAR] = self.STRING
		self.cube[self.STRING, self.EQUAL, self.STRING] = self.STRING
		self.cube[self.STRING, self.EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.EQUAL, self.NULL] = self.ERROR
		#  STRING != Data types
		self.cube[self.STRING, self.NOT_EQUAL, self.INT] = self.ERROR
		self.cube[self.STRING, self.NOT_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.NOT_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.NOT_EQUAL, self.STRING] = self.ERROR
		self.cube[self.STRING, self.NOT_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.NOT_EQUAL, self.NULL] = self.ERROR
		#  STRING && Data types
		self.cube[self.STRING, self.AND, self.INT] = self.ERROR
		self.cube[self.STRING, self.AND, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.AND, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.AND, self.STRING] = self.ERROR
		self.cube[self.STRING, self.AND, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.AND, self.NULL] = self.ERROR
		#  STRING && Data types
		self.cube[self.STRING, self.OR, self.INT] = self.ERROR
		self.cube[self.STRING, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.STRING, self.OR, self.CHAR] = self.ERROR
		self.cube[self.STRING, self.OR, self.STRING] = self.ERROR
		self.cube[self.STRING, self.OR, self.BOOLEAN] = self.ERROR
		self.cube[self.STRING, self.OR, self.NULL] = self.ERROR
		# BOOLEAN + Data types
		self.cube[self.BOOLEAN, self.SUM, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.SUM, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.SUM, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.SUM, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.SUM, self.BOOLEAN] = self.ERROR
		self.cube[self.BOOLEAN, self.SUM, self.NULL] = self.ERROR
		# BOOLEAN - Data types
		self.cube[self.BOOLEAN, self.SUBSTRACTION, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.SUBSTRACTION, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.SUBSTRACTION, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.SUBSTRACTION, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.SUBSTRACTION, self.BOOLEAN] = self.ERROR
		self.cube[self.BOOLEAN, self.SUBSTRACTION, self.NULL] = self.ERROR
		# BOOLEAN * Data types
		self.cube[self.BOOLEAN, self.MULTIPLICATION, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.MULTIPLICATION, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.MULTIPLICATION, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.MULTIPLICATION, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.MULTIPLICATION, self.BOOLEAN] = self.ERROR
		self.cube[self.BOOLEAN, self.MULTIPLICATION, self.NULL] = self.ERROR
		# BOOLEAN / Data types
		self.cube[self.BOOLEAN, self.DIVISION, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.DIVISION, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.DIVISION, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.DIVISION, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.DIVISION, self.BOOLEAN] = self.ERROR
		self.cube[self.BOOLEAN, self.DIVISION, self.NULL] = self.ERROR
		# BOOLEAN Power Data types
		self.cube[self.BOOLEAN, self.POWER, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.POWER, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.POWER, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.POWER, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.POWER, self.BOOLEAN] = self.ERROR
		self.cube[self.BOOLEAN, self.POWER, self.NULL] = self.ERROR
		# BOOLEAN MOD Data types
		self.cube[self.BOOLEAN, self.MOD, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.MOD, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.MOD, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.MOD, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.MOD, self.BOOLEAN] = self.ERROR
		self.cube[self.BOOLEAN, self.MOD, self.NULL] = self.ERROR
		# BOOLEAN GREATER Data types
		self.cube[self.BOOLEAN, self.GREATER, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.GREATER, self.NULL] = self.ERROR
		# BOOLEAN LESS Data types
		self.cube[self.BOOLEAN, self.LESS, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.LESS, self.NULL] = self.ERROR
		# BOOLEAN >= Data types
		self.cube[self.BOOLEAN, self.GREATER_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.GREATER_OR_EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.GREATER_OR_EQUAL, self.NULL] = self.ERROR
		# BOOLEAN <= Data types
		self.cube[self.BOOLEAN, self.LESS_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.LESS_OR_EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.LESS_OR_EQUAL, self.NULL] = self.ERROR
		# BOOLEAN = Data types
		self.cube[self.BOOLEAN, self.EQUAL, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.EQUAL, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.EQUAL, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.EQUAL, self.NULL] = self.ERROR
		# BOOLEAN != Data types
		self.cube[self.BOOLEAN, self.NOT_EQUAL, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.NOT_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.NOT_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.NOT_EQUAL, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.NOT_EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.NOT_EQUAL, self.NULL] = self.ERROR
		# BOOLEAN AND Data types
		self.cube[self.BOOLEAN, self.AND, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.AND, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.AND, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.AND, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.AND, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.AND, self.NULL] = self.ERROR
		# BOOLEAN OR Data types
		self.cube[self.BOOLEAN, self.OR, self.INT] = self.ERROR
		self.cube[self.BOOLEAN, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.BOOLEAN, self.OR, self.CHAR] = self.ERROR
		self.cube[self.BOOLEAN, self.OR, self.STRING] = self.ERROR
		self.cube[self.BOOLEAN, self.OR, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.BOOLEAN, self.OR, self.NULL] = self.ERROR
		# NULL + Data types
		self.cube[self.NULL, self.SUM, self.INT] = self.ERROR
		self.cube[self.NULL, self.SUM, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.SUM, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.SUM, self.STRING] = self.ERROR
		self.cube[self.NULL, self.SUM, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.SUM, self.NULL] = self.ERROR
		# NULL - Data types
		self.cube[self.NULL, self.SUBSTRACTION, self.INT] = self.ERROR
		self.cube[self.NULL, self.SUBSTRACTION, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.SUBSTRACTION, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.SUBSTRACTION, self.STRING] = self.ERROR
		self.cube[self.NULL, self.SUBSTRACTION, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.SUBSTRACTION, self.NULL] = self.ERROR
		# NULL * Data types
		self.cube[self.NULL, self.MULTIPLICATION, self.INT] = self.ERROR
		self.cube[self.NULL, self.MULTIPLICATION, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.MULTIPLICATION, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.MULTIPLICATION, self.STRING] = self.ERROR
		self.cube[self.NULL, self.MULTIPLICATION, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.MULTIPLICATION, self.NULL] = self.ERROR
		# NULL / Data types
		self.cube[self.NULL, self.DIVISION, self.INT] = self.ERROR
		self.cube[self.NULL, self.DIVISION, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.DIVISION, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.DIVISION, self.STRING] = self.ERROR
		self.cube[self.NULL, self.DIVISION, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.DIVISION, self.NULL] = self.ERROR
		# NULL Power Data types
		self.cube[self.NULL, self.POWER, self.INT] = self.ERROR
		self.cube[self.NULL, self.POWER, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.POWER, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.POWER, self.STRING] = self.ERROR
		self.cube[self.NULL, self.POWER, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.POWER, self.NULL] = self.ERROR
		# NULL MOD Data types
		self.cube[self.NULL, self.MOD, self.INT] = self.ERROR
		self.cube[self.NULL, self.MOD, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.MOD, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.MOD, self.STRING] = self.ERROR
		self.cube[self.NULL, self.MOD, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.MOD, self.NULL] = self.ERROR
		# NULL GREATER Data types
		self.cube[self.NULL, self.GREATER, self.INT] = self.ERROR
		self.cube[self.NULL, self.GREATER, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.GREATER, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.GREATER, self.STRING] = self.ERROR
		self.cube[self.NULL, self.GREATER, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.GREATER, self.NULL] = self.ERROR
		# NULL >= Data types
		self.cube[self.NULL, self.GREATER_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.NULL, self.GREATER_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.GREATER_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.GREATER_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.NULL, self.GREATER_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.GREATER_OR_EQUAL, self.NULL] = self.ERROR
		# NULL <= Data types
		self.cube[self.NULL, self.LESS_OR_EQUAL, self.INT] = self.ERROR
		self.cube[self.NULL, self.LESS_OR_EQUAL, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.LESS_OR_EQUAL, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.LESS_OR_EQUAL, self.STRING] = self.ERROR
		self.cube[self.NULL, self.LESS_OR_EQUAL, self.BOOLEAN] = self.ERROR
		self.cube[self.NULL, self.LESS_OR_EQUAL, self.NULL] = self.ERROR
		# NULL = Data types
		self.cube[self.NULL, self.EQUAL, self.INT] = self.INT
		self.cube[self.NULL, self.EQUAL, self.FLOAT] = self.FLOAT
		self.cube[self.NULL, self.EQUAL, self.CHAR] = self.CHAR
		self.cube[self.NULL, self.EQUAL, self.STRING] = self.STRING
		self.cube[self.NULL, self.EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.NULL, self.EQUAL, self.NULL] = self.NULL
		# NULL = Data types
		self.cube[self.NULL, self.EQUAL, self.INT] = self.INT
		self.cube[self.NULL, self.EQUAL, self.FLOAT] = self.FLOAT
		self.cube[self.NULL, self.EQUAL, self.CHAR] = self.CHAR
		self.cube[self.NULL, self.EQUAL, self.STRING] = self.STRING
		self.cube[self.NULL, self.EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.NULL, self.EQUAL, self.NULL] = self.NULL
		# NULL != Data types
		self.cube[self.NULL, self.NOT_EQUAL, self.INT] = self.BOOLEAN
		self.cube[self.NULL, self.NOT_EQUAL, self.FLOAT] = self.BOOLEAN
		self.cube[self.NULL, self.NOT_EQUAL, self.CHAR] = self.BOOLEAN
		self.cube[self.NULL, self.NOT_EQUAL, self.STRING] = self.BOOLEAN
		self.cube[self.NULL, self.NOT_EQUAL, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.NULL, self.NOT_EQUAL, self.NULL] = self.BOOLEAN
		# NULL AND Data types
		self.cube[self.NULL, self.AND, self.INT] = self.ERROR
		self.cube[self.NULL, self.AND, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.AND, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.AND, self.STRING] = self.ERROR
		self.cube[self.NULL, self.AND, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.NULL, self.AND, self.NULL] = self.ERROR
		# NULL OR Data types
		self.cube[self.NULL, self.OR, self.INT] = self.ERROR
		self.cube[self.NULL, self.OR, self.FLOAT] = self.ERROR
		self.cube[self.NULL, self.OR, self.CHAR] = self.ERROR
		self.cube[self.NULL, self.OR, self.STRING] = self.ERROR
		self.cube[self.NULL, self.OR, self.BOOLEAN] = self.BOOLEAN
		self.cube[self.NULL, self.OR, self.NULL] = self.ERROR



	def getDataType(self, operand1, operation, operand2):
		return self.cube[operand1, operation, operand2]

if __name__ == "__main__":
	cube = Cube()
	print(cube.getDataType(0, 0, 3))